//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymManagementApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int idSchedule { get; set; }
        public int idTrainer { get; set; }
        public int idApparatus { get; set; }
        public Nullable<System.DateTime> timeTraining { get; set; }
    
        public virtual Apparatus Apparatus { get; set; }
        public virtual Trainers Trainers { get; set; }
    }
}
